### ISSUE TITLE
Crash due to unrecognised selector sent to instance

### ISSUE THREAD

**Issue by cpellet** [leanflutter/flutter_svprogresshud#14]
Calling `SVProgressHUD.showSuccess();` leads to the following error:

`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull length]: unrecognized selector sent to instance 0x1fb1a7a88'
terminating with uncaught exception of type NSException`

This happens all the time

(see more in screenshot below)
![Screenshot 2022-06-29 at 15 16 05](https://user-images.githubusercontent.com/18552249/176446201-dabb4a48-2f9f-4b27-9df9-be601c15629f.png)

**Comment by elceka** [comment]
BUMP

**Comment by elceka** [comment]
In the method _SVProgressHUD.showSuccess()_ you must define the _status_ parameter, _status_ parameter can't be a null, it can be empty but not null.

**Comment by lijy91** [comment]
The status parameter has been set as required
