### ISSUE TITLE
Namespace not specified. Specify a namespace in the module's build file. 

### ISSUE THREAD

**Issue by bink-develop** [leanflutter/flutter_svprogresshud#17]
Hello, I meet this error，can you add namespace for AGP8 compatibility.

A problem occurred configuring project ':flutter_svprogresshud'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

**Comment by zakblacki** [comment]
any solution

**Comment by lijy91** [comment]
Please provide a minimal reproducible example

**Comment by lijy91** [comment]
Fixed, please update to 1.1.0
